'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4200
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BlitzCards.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Public ReadOnly Property aceclubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aceclubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property aceclubsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aceclubsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property acediamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("acediamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property acediamondsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("acediamondsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property acehearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("acehearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property aceheartsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aceheartsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property acespades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("acespades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property acespadesi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("acespadesi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property blueback() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueback", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bluebacki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bluebacki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property eightclubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eightclubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property eightclubsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eightclubsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property eightdiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eightdiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property eightdiamondsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eightdiamondsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property eighthearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eighthearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property eightheartsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eightheartsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property eightspades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eightspades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property eightspadesi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eightspadesi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property fiveclubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fiveclubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property fiveclubsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fiveclubsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property fivediamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fivediamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property fivediamondsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fivediamondsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property fivehearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fivehearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property fiveheartsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fiveheartsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property fivespades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fivespades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property fivespadesi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fivespadesi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property fourclubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fourclubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property fourclubsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fourclubsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property fourdiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fourdiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property fourdiamondsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fourdiamondsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property fourhearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fourhearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property fourheartsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fourheartsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property fourspades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fourspades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property fourspadesi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fourspadesi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property jackclubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jackclubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property jackclubsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jackclubsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property jackdiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jackdiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property jackdiamondsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jackdiamondsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property jackhearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jackhearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property jackheartsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jackheartsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property jackspades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jackspades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property jackspadesi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jackspadesi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property kingclubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kingclubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property kingclubsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kingclubsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property kingdiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kingdiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property kingdiamondsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kingdiamondsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property kinghearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kinghearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property kingheartsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kingheartsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property kingspades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kingspades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property kingspadesi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kingspadesi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property nineclubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nineclubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property nineclubsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nineclubsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ninediamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ninediamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ninediamondsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ninediamondsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ninehearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ninehearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property nineheartsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nineheartsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ninespades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ninespades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ninespadesi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ninespadesi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property queenclubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("queenclubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property queenclubsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("queenclubsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property queendiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("queendiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property queendiamondsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("queendiamondsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property queenhearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("queenhearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property queenheartsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("queenheartsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property queenspades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("queenspades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property queenspadesi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("queenspadesi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property sevenclubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sevenclubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property sevenclubsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sevenclubsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property sevendiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sevendiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property sevendiamondsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sevendiamondsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property sevenhearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sevenhearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property sevenheartsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sevenheartsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property sevenspades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sevenspades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property sevenspadesi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sevenspadesi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property sixclubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sixclubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property sixclubsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sixclubsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property sixdiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sixdiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property sixdiamondsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sixdiamondsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property sixhearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sixhearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property sixheartsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sixheartsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property sixspades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sixspades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property sixspadesi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sixspadesi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property tenclubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tenclubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property tenclubsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tenclubsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property tendiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tendiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property tendiamondsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tendiamondsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property tenhearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tenhearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property tenheartsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tenheartsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property tenspades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tenspades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property tenspadesi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tenspadesi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property threeclubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("threeclubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property threeclubsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("threeclubsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property threediamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("threediamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property threediamondsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("threediamondsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property threehearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("threehearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property threeheartsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("threeheartsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property threespades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("threespades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property threespadesi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("threespadesi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property twoclubs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twoclubs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property twoclubsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twoclubsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property twodiamonds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twodiamonds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property twodiamondsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twodiamondsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property twohearts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twohearts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property twoheartsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twoheartsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property twospades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twospades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property twospadesi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twospadesi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
